//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XpeulMedia.rc
//
#define IDS_REGSVR_LRCFLDR_INFO			50
#define IDS_REGSVR_LRCFLDR_DEFAULT		51

#define IDS_EFFECT_NAME							100
#define IDS_EFFECT_DESCRIPTION				101
#define IDS_EFFECT_PROPERTYPAGE_INFO	102
#define IDS_EFFECT_PRESET_H					115
#define IDS_EFFECT_PRESET_V						116
#define IDS_EFFECT_PRESET_B						117
#define IDS_EFFECT_PARSING_EMBED			147
#define IDS_EFFECT_PARSING_FILE				148
#define IDS_EFFECT_PARSED_NOLYRICS		149
#define IDS_EFFECT_INTERNAL_ERROR		150

#define IDS_BACK_NAME							200
#define IDS_BACK_DESCRIPTION					201
#define IDS_BACK_PROPERTYPAGE_INFO		202
#define IDS_BACK_VIDEOMENU_TOPMOST	210
#define IDS_BACK_VIDEOMENU_FULLMODE	211
#define IDS_BACK_VIDEOMENU_PLAYCTRL	212
#define IDS_BACK_VIDEOMENU_PLAYLIST	213
#define IDS_BACK_VIDEOMENU_OPTIONS	214

#define IDS_SCRNSVR_NAME							300
#define IDS_SCRNSVR_DESCRIPTION				301
#define IDS_SCRNSVR_PROPERTYPAGE_INFO	302

#define IDR_RGS_EFFECT						1101
#define IDR_RGS_BACK							1102
#define IDR_RGS_SCRNSVR						1103

#define IDI_TRAYICON							1200
#define IDM_CONTEXTMENU					1250

#define ID_MainUI_OPEN						4500
#define ID_MainUI_RESTORE					4501
#define ID_MainUI_CLOSE						4502

#define ID_MainUI_TOPMOST					4500
#define ID_MainUI_FULLMODE				4501
#define __DONTUSE_ID_MainUI_PLAYCTRL_FIRST			4600
#define ID_MainUI_PLAYCTRL_PLAYPAUSE	4601
#define ID_MainUI_PLAYCTRL_STOP				4602
#define ID_MainUI_PLAYCTRL_PREV				4603
#define ID_MainUI_PLAYCTRL_NEXT				4604
#define ID_MainUI_PLAYCTRL_MUTE			4605
#define __DONTUSE_ID_MainUI_PLAYCTRL_LAST			4799
#define __DONTUSE_ID_MainUI_PLAYLIST_FIRST			4800
#define ID_MainUI_PLAYLIST_EDITOR		4801
#define ID_MainUI_PLAYLIST_ADDFILES		4802
#define ID_MainUI_PLAYLIST_ADDFOLDER	4803
#define ID_MainUI_PLAYLIST_CLEAR			4804
#define ID_MainUI_PLAYLIST_ORDER_NAME_UP	4805
#define ID_MainUI_PLAYLIST_ORDER_NAME_DOWN	4806
#define ID_MainUI_PLAYLIST_ORDER_TITLE_UP	4805
#define ID_MainUI_PLAYLIST_ORDER_TITLE_DOWN	4806
#define ID_MainUI_PLAYLIST_ORDER_RANDOM	4807
#define ID_MainUI_PLAYLIST_ITEM_FIRST	4808
#define ID_MainUI_PLAYLIST_ITEM_LAST	4907
#define __DONTUSE_ID_MainUI_PLAYLIST_LAST		4999
#define __DONTUSE_ID_MainUI_OPTION_FIRST		5000
#define ID_MainUI_OPTION_OPTIONS		5000
#define ID_MainUI_OPTION_UPDATE		5197
#define ID_MainUI_OPTION_ABOUT		5198
#define ID_MainUI_OPTION_HELP			5199
#define __DONTUSE_ID_MainUI_OPTION_LAST		5199

#define ID_TrayIcon_OPEN						4510
#define ID_TrayIcon_RESTORE					4511
#define ID_TrayIcon_CLOSE						4512
#define ID_TrayIcon_PLAYPAUSE				4513
#define ID_TrayIcon_STOP						4514
#define ID_TrayIcon_PREV						4515
#define ID_TrayIcon_NEXT						4516
#define ID_TrayIcon_MUTE						4517
#define ID_TrayIcon_NOTHING				4518


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40022
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
